apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: private-reg-container
    image: jesus-private
    imagePullPolicy: IfNotPresent
  imagePullSecrets:
  - name: regcred